// Generated by CoffeeScript 1.4.0
(function() {
  var expect;

  expect = (typeof chai !== "undefined" && chai !== null ? chai.expect : void 0) || require('chai').expect;

  describe('Tests Mixed', function() {
    it('passes 1', function() {
      return expect(1).to.be.ok;
    });
    it('passes 2', function() {
      return expect(2).to.be.ok;
    });
    it('passes 3', function() {
      return expect(3).to.be.ok;
    });
    it('skips 1');
    it('skips 2');
    it('skips 3');
    it('fails 1', function() {
      return expect(false).to.be["true"];
    });
    it('fails 2', function() {
      return expect(false).to.be["true"];
    });
    it('fails 3', function() {
      return expect(false).to.be["true"];
    });
    it('passes 4', function() {
      return expect(1).to.be.ok;
    });
    it('passes 5', function() {
      return expect(2).to.be.ok;
    });
    it('passes 6', function() {
      return expect(3).to.be.ok;
    });
    it('fails 4', function() {
      return expect(false).to.be["true"];
    });
    it('fails 5', function() {
      return expect(false).to.be["true"];
    });
    it('fails 6', function() {
      return expect(false).to.be["true"];
    });
    it('skips 4');
    it('skips 5');
    return it('skips 6');
  });

}).call(this);
