// Generated by CoffeeScript 1.3.3
(function() {
  var expect;

  expect = (typeof chai !== "undefined" && chai !== null ? chai.expect : void 0) || require('chai').expect;

  describe('Tests Passing', function() {
    it('passes 1', function() {
      return expect(1).to.be.ok;
    });
    it('passes 2', function() {
      return expect(2).to.be.ok;
    });
    it('passes 3', function() {
      return expect(3).to.be.ok;
    });
    it('skips 1');
    it('skips 2');
    return it('skips 3');
  });

}).call(this);
