// Generated by CoffeeScript 1.6.3
(function() {
  define(['passing'], function(require) {
    if (window.mochaPhantomJS) {
      return mochaPhantomJS.run();
    } else {
      return mocha.run();
    }
  });

}).call(this);
