// Generated by CoffeeScript 1.4.0
(function() {

  define(['passing'], function(require) {
    if (window.mochaPhantomJS) {
      return mochaPhantomJS.run();
    } else {
      return mocha.run();
    }
  });

}).call(this);
